spring:
  jackson:
    time-zone: Asia/Shanghai
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 512MB

### Druid 配置
spring.datasource:
    druid:
      validation-query: SELECT 1
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filter:
        wall:
          enabled: true
          db-type: mysql
        stat:
          enabled: true
          db-type: mysql
      connection-properties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: .js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin

### MyBatis Plus 配置
mybatis-plus:
  global-config:
    banner: off

### Actuator 配置
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
