server:
  port: 10240
spring:
  application:
    name: vertex-application
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis-plus:
  global-config:
    banner: off