application:
  version: '@project.version@'

spring:
  jackson:
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 512MB
  datasource:
    druid:
      validation-query: SELECT 1
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,slf4j
      connection-properties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: .js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
  liquibase:
    enabled: false
    change-log: classpath:changelog/mysql/changelog-application.xml
    database-change-log-table: xv_database_changelog
    database-change-log-lock-table: vx_database_changelog_lock
  mail:
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory

# MyBatis Plus 配置
mybatis-plus:
  global-config:
    banner: off

# Spring Boot Actuator 配置
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}