# Develop Environment Configurations
spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://db.onezol.com:3306/vertex?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: vertex
    password: XrZZNKcDJhwEbaYF
  # Redis配置
  data:
    redis:
      host: redis.onezol.com
      port: 6379
      password: 123456
      database: 5
  # 邮件配置
  mail:
    host: smtp.exmail.qq.com
    port: 465
    username: mail@onezol.com
    password: JYGtUgkah6x89BLc
  # MQTT配置
  mqtt:
    enabled: true
    broker-url: tcp://onezol.com:1883
    client-id: ${spring.application.name}
    username: admin
    password: public

# 应用配置
application:
  jwt:
    secret-key: C61270901C4A455A89A0196CBCED9803
    expiration-time: 3600  # token有效期, 1小时

# 日志配置
logging:
  level:
    root: info
    com.onezol.vertex: debug