# Base Environment Configurations
application:
  version: '@project.version@'

server:
  port: 10240
spring:
  application:
    name: vertex-application
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 64MB
      max-file-size: 256MB
      max-request-size: 512MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      validation-query: SELECT 1
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,slf4j
      connection-properties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: .js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
  data:
    redis:
      timeout: 10000
      connect-timeout: 15000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: 200ms
          time-between-eviction-runs: 30s
  liquibase:
    enabled: false
    change-log: classpath:changelog/mysql/changelog-application.xml
    database-change-log-table: xv_database_changelog
    database-change-log-lock-table: vx_database_changelog_lock
  mail:
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
mybatis-plus:
  global-config:
    banner: off

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
